// Survey questions derived from content/pre-workshop/survey.md

export const sections = [
  { id: 'where-you-are', title: 'Where You Are' },
  { id: 'current-workflow', title: 'Current Workflow' },
  { id: 'pain-points', title: 'Pain Points' },
  { id: 'your-stack', title: 'Your Stack (Quick Hits)' },
  { id: 'open-ended', title: 'Open-Ended (Optional)' },
]

export const questions = [
  {
    id: 'q1_yegge_stage',
    section: 'where-you-are',
    title: 'Where are you on the AI-assisted coding ladder?',
    hint: 'Pick the stage that best describes your current daily workflow',
    type: 'radio',
    options: [
      { value: '1', label: 'Stage 1: Zero or near-zero AI', desc: 'Maybe code completions, sometimes ask Chat questions' },
      { value: '2', label: 'Stage 2: Agent in IDE, permissions on', desc: 'A narrow agent in a sidebar asks permission to run tools' },
      { value: '3', label: 'Stage 3: Agent in IDE, YOLO mode', desc: 'Trust goes up, permissions off, agent gets wider' },
      { value: '4', label: 'Stage 4: In IDE, wide agent', desc: 'Agent fills the screen, code is just for diffs' },
      { value: '5', label: 'Stage 5: CLI, single agent, YOLO', desc: 'Diffs scroll by, you may or may not look at them' },
      { value: '6', label: 'Stage 6: CLI, multi-agent, YOLO', desc: '3-5 parallel instances, very fast' },
      { value: '7', label: 'Stage 7: 10+ agents, hand-managed', desc: 'Pushing limits of manual coordination' },
      { value: '8', label: 'Stage 8: Building your own orchestrator', desc: 'Automating your workflow on the frontier' },
    ],
  },
  {
    id: 'q2_os',
    section: 'where-you-are',
    title: 'What OS do you use for development?',
    type: 'radio',
    options: [
      { value: 'macos', label: 'macOS' },
      { value: 'windows', label: 'Windows' },
      { value: 'linux', label: 'Linux' },
      { value: 'wsl', label: 'WSL on Windows' },
      { value: 'other', label: 'Other' },
    ],
  },
  {
    id: 'q3_ai_tools',
    section: 'where-you-are',
    title: 'What AI tools are you currently using?',
    hint: 'Select all that apply',
    type: 'checkbox',
    options: [
      { value: 'claude_code_cli', label: 'Claude Code (CLI)' },
      { value: 'claude_code_ide', label: 'Claude Code in VS Code / IDE' },
      { value: 'copilot', label: 'Copilot' },
      { value: 'cursor', label: 'Cursor' },
      { value: 'gemini', label: 'Gemini' },
      { value: 'chatgpt', label: 'ChatGPT' },
      { value: 'other', label: 'Other' },
    ],
  },
  {
    id: 'q4_subscription',
    section: 'where-you-are',
    title: 'What Claude subscription tier are you on?',
    type: 'radio',
    options: [
      { value: 'free', label: 'Free' },
      { value: 'pro', label: 'Pro ($20/mo)' },
      { value: 'max_5x', label: 'Max 5x ($100/mo)' },
      { value: 'max_20x', label: 'Max 20x ($200/mo)' },
      { value: 'team', label: 'Team plan' },
      { value: 'unsure', label: 'Not sure' },
    ],
  },
  {
    id: 'q5_features',
    section: 'current-workflow',
    title: 'Which Claude Code features do you currently use?',
    hint: 'Select all that apply',
    type: 'checkbox',
    options: [
      { value: 'yolo', label: 'YOLO mode (--dangerously-skip-permissions)' },
      { value: 'planning', label: 'Planning mode' },
      { value: 'custom_skills', label: 'Custom skills or commands' },
      { value: 'compact_clear', label: '/compact or /clear for context management' },
      { value: 'github', label: 'GitHub integration (@claude on issues/PRs)' },
      { value: 'slack', label: 'Slack integration' },
      { value: 'mcp', label: 'MCP servers' },
      { value: 'none', label: 'None of the above / not sure' },
    ],
  },
  {
    id: 'q6_claude_md',
    section: 'current-workflow',
    title: 'Do you currently have CLAUDE.md files in your repositories?',
    type: 'radio',
    options: [
      { value: 'yes_most', label: 'Yes, most or all repos' },
      { value: 'yes_some', label: 'Yes, some repos' },
      { value: 'no_know', label: 'No, but I know what they are' },
      { value: 'no_unsure', label: "No, and I'm not sure what they are" },
    ],
  },
  {
    id: 'q7_frequency',
    section: 'current-workflow',
    title: 'How often do you use Claude Code?',
    type: 'radio',
    options: [
      { value: 'daily', label: 'Daily' },
      { value: 'several_week', label: 'Several times a week' },
      { value: 'weekly', label: 'Weekly' },
      { value: 'occasionally', label: 'Occasionally' },
      { value: 'not_started', label: "Haven't started yet" },
    ],
  },
  {
    id: 'q8_challenges',
    section: 'pain-points',
    title: 'Which of these challenges have you experienced with AI-assisted development?',
    hint: 'Select all that apply',
    type: 'checkbox',
    options: [
      { value: 'ai_slop', label: 'AI generates code that looks right but has subtle bugs ("AI slop")' },
      { value: 'domain', label: 'Getting AI to understand our domain terminology and patterns' },
      { value: 'big_diffs', label: 'Diffs that are too large to review effectively' },
      { value: 'outdated', label: 'AI using outdated documentation or deprecated patterns' },
      { value: 'repeating', label: 'Repeating the same context in every new conversation' },
      { value: 'cross_repo', label: 'Cross-repo changes are difficult' },
      { value: 'code_review', label: 'Code review friction with AI-generated code' },
      { value: 'skip_process', label: 'Skipping process because AI makes it fast' },
      { value: 'other', label: 'Other' },
    ],
  },
  {
    id: 'q9_hopes',
    section: 'pain-points',
    title: 'What are you most hoping to get out of this workshop?',
    hint: 'Select up to 3',
    type: 'checkbox',
    max: 3,
    options: [
      { value: 'best_practices', label: "Best practices I'm missing in my current workflow" },
      { value: 'pain_points', label: 'Solving specific pain points (big diffs, domain modeling, etc.)' },
      { value: 'claude_md', label: 'Structuring CLAUDE.md and project configuration' },
      { value: 'mcp', label: 'Learning about MCP and integrations' },
      { value: 'which_tool', label: 'Understanding when to use which AI tool' },
      { value: 'cost', label: 'Cost and token efficiency' },
      { value: 'templates', label: 'Templates and references I can use immediately' },
      { value: 'automation', label: 'Moving from "pair programmer" to automation/orchestration' },
    ],
  },
  {
    id: 'q10_time_split',
    section: 'pain-points',
    title: 'Where should we spend more time?',
    hint: 'The Crash Course covers fundamentals. The Advanced section covers agents, orchestration, and frontier patterns.',
    type: 'radio',
    options: [
      { value: 'crash_course', label: 'More time on the Crash Course', desc: 'I want to nail the fundamentals and build a strong foundation' },
      { value: 'advanced', label: 'More time on Advanced', desc: "I've got the basics, push me further" },
      { value: 'equal', label: 'Equal time on both', desc: 'A balanced mix' },
    ],
  },
  {
    id: 'q11_test_frameworks',
    section: 'your-stack',
    title: 'What test frameworks do you use?',
    hint: 'Select all that apply',
    type: 'checkbox',
    options: [
      { value: 'rspec', label: 'RSpec' },
      { value: 'jest', label: 'Jest' },
      { value: 'playwright', label: 'Playwright' },
      { value: 'cypress', label: 'Cypress' },
      { value: 'go_testing', label: 'Go testing' },
      { value: 'other', label: 'Other' },
    ],
  },
  {
    id: 'q12_docs',
    section: 'your-stack',
    title: 'Where do you look for documentation?',
    hint: 'Select all that apply',
    type: 'checkbox',
    options: [
      { value: 'confluence', label: 'Confluence' },
      { value: 'notion', label: 'Notion' },
      { value: 'markdown', label: 'Markdown in repos' },
      { value: 'gdocs', label: 'Google Docs' },
      { value: 'readme', label: 'README files' },
      { value: 'other', label: 'Other' },
    ],
  },
  {
    id: 'q13_tools_used',
    section: 'your-stack',
    title: 'Have you used any of these?',
    hint: 'Select all that apply',
    type: 'checkbox',
    options: [
      { value: 'worktrees', label: 'Git worktrees' },
      { value: 'graphite', label: 'Graphite or other PR stacking tools' },
      { value: 'notebooklm', label: 'NotebookLM' },
      { value: 'ai_studio', label: 'Google AI Studio' },
      { value: 'none', label: 'None of the above' },
    ],
  },
  {
    id: 'q14_excited',
    section: 'open-ended',
    title: 'What specific workflow or task are you most excited to improve with AI?',
    type: 'text',
    optional: true,
  },
  {
    id: 'q15_anything_else',
    section: 'open-ended',
    title: 'Anything else you want us to cover in the workshop?',
    type: 'text',
    optional: true,
  },
]
