// Survey questions for Claude Code Workshop pre-survey

export const sections = [
  { id: 'your-workflow', title: 'Your Workflow' },
  { id: 'claude-code', title: 'Claude Code' },
  { id: 'pain-points', title: 'Pain Points & Priorities' },
]

export const questions = [
  {
    id: 'q1_workflow',
    section: 'your-workflow',
    title: 'Which of these are part of your current workflow?',
    hint: 'Select all that apply — ordered from basic to advanced',
    type: 'checkbox',
    options: [
      { value: 'chat', label: 'Chat (copy/paste between browser and editor)' },
      { value: 'autocomplete', label: 'In-IDE autocomplete (Copilot suggestions, etc.)' },
      { value: 'ide_agent', label: 'In-IDE agent (Cursor, Claude in VS Code, etc.)' },
      { value: 'plan_mode', label: 'Plan mode' },
      { value: 'context_mgmt', label: 'Context management (/clear, fresh conversations)' },
      { value: 'yolo', label: 'YOLO mode (auto-approve permissions)' },
      { value: 'custom_commands', label: 'Custom slash commands or skills' },
      { value: 'hooks', label: 'Hooks (pre/post action automation)' },
      { value: 'mcp', label: 'MCP servers' },
      { value: 'multi_agent', label: 'Multi-agent / parallel sessions' },
    ],
  },
  {
    id: 'q2_role',
    section: 'your-workflow',
    title: "What's your primary focus?",
    type: 'radio',
    options: [
      { value: 'backend', label: 'Backend' },
      { value: 'frontend', label: 'Frontend' },
      { value: 'fullstack', label: 'Full-stack' },
      { value: 'devops', label: 'DevOps / Infrastructure' },
      { value: 'qa', label: 'QA / Testing' },
      { value: 'management', label: 'Engineering Management' },
    ],
  },
  {
    id: 'q3_ai_setup',
    section: 'your-workflow',
    title: 'Describe your AI workflow — what tools, frameworks, or custom setups do you use with Claude or other AI assistants?',
    type: 'text',
    optional: true,
    placeholder: 'e.g. "Claude Code CLI with custom MCP servers for Jira, Copilot for autocomplete, ChatGPT for brainstorming..."',
  },
  {
    id: 'q4_subscription',
    section: 'claude-code',
    title: 'What Claude subscription tier are you on?',
    type: 'radio',
    options: [
      { value: 'none', label: "I don't use Claude" },
      { value: 'free', label: 'Free' },
      { value: 'pro', label: 'Pro ($20/mo)' },
      { value: 'max_5x', label: 'Max 5x ($100/mo)' },
      { value: 'max_20x', label: 'Max 20x ($200/mo)' },
      { value: 'team', label: 'Team plan' },
      { value: 'unsure', label: 'Not sure' },
    ],
  },
  {
    id: 'q5_claude_md',
    section: 'claude-code',
    title: 'Rate your familiarity with CLAUDE.md files',
    type: 'radio',
    options: [
      { value: 'never_heard', label: 'Never heard of them' },
      { value: 'heard_of', label: "Heard of them but haven't set one up" },
      { value: 'basic', label: 'Have a basic one in a repo or two' },
      { value: 'regular', label: 'Use them regularly and keep them updated' },
      { value: 'advanced', label: 'Advanced (nested project/repo-level files, shared team conventions)' },
    ],
  },
  {
    id: 'q6_vibecoding',
    section: 'pain-points',
    title: 'How do you feel about "vibe coding" — letting AI generate code without fully reviewing every line?',
    type: 'radio',
    options: [
      { value: 'excited', label: 'Mostly excited', desc: "It's the future, let's go" },
      { value: 'cautious_optimism', label: 'Cautiously optimistic', desc: 'I see the potential but want guardrails' },
      { value: 'mixed', label: 'Mixed feelings', desc: 'Excited and concerned in equal measure' },
      { value: 'concerned', label: 'Mostly concerned', desc: 'Worried about quality, security, or understanding' },
      { value: 'opposed', label: "Not for me", desc: 'I want to understand every line that ships' },
    ],
  },
  {
    id: 'q7_challenges',
    section: 'pain-points',
    title: 'Which of these challenges have you experienced with AI-assisted development?',
    hint: 'Select all that apply',
    type: 'checkbox',
    options: [
      { value: 'ai_slop', label: 'AI generates code that looks right but has subtle bugs ("AI slop")' },
      { value: 'domain', label: 'Getting AI to understand our domain terminology and patterns' },
      { value: 'big_diffs', label: 'Diffs that are too large to review effectively' },
      { value: 'outdated', label: 'AI using outdated documentation or deprecated patterns' },
      { value: 'repeating', label: 'Repeating the same context in every new conversation' },
      { value: 'cross_repo', label: 'Cross-repo changes are difficult' },
      { value: 'code_review', label: 'Code review friction with AI-generated code' },
      { value: 'skip_process', label: 'Skipping process because AI makes it fast' },
      { value: 'other', label: 'Other' },
    ],
  },
  {
    id: 'q8_time_split',
    section: 'pain-points',
    title: 'Where should we spend more time?',
    hint: 'The Crash Course covers fundamentals. The Advanced section covers agents, orchestration, and frontier patterns.',
    type: 'radio',
    options: [
      { value: 'crash_course', label: 'More time on the Crash Course', desc: 'I want to nail the fundamentals and build a strong foundation' },
      { value: 'advanced', label: 'More time on Advanced', desc: "I've got the basics, push me further" },
      { value: 'equal', label: 'Equal time on both', desc: 'A balanced mix' },
    ],
  },
]
